# You shouldn't need to edit this file

[store]
dir = "target"

[profile.default]
retries = 0
status-level = "pass"
fail-fast = false
slow-timeout = "10s"

[profile.default.junit]
path = "junit.xml"

report-name = "nextest-run"